# Generated by Django 5.1.7 on 2025-04-01 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_user_type_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('health', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('energy', 'Energy')], default='tech', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, default='http://www.example.com', null=True),
        ),
    ]
